export const MAHARASHTRA_DISTRICTS: string[] = [
  "Ahmednagar",
  "Akola",
  "Amravati",
  "Aurangabad",
  "Beed",
  "Bhandara",
  "Buldhana",
  "Chandrapur",
  "Dhule",
  "Gadchiroli",
  "Gondia",
  "Hingoli",
  "Jalgaon",
  "Jalna",
  "Kolhapur",
  "Latur",
  "Mumbai City",
  "Mumbai Suburban",
  "Nagpur",
  "Nanded",
  "Nandurbar",
  "Nashik",
  "Osmanabad",
  "Palghar",
  "Parbhani",
  "Pune",
  "Raigad",
  "Ratnagiri",
  "Sangli",
  "Satara",
  "Sindhudurg",
  "Solapur",
  "Thane",
  "Wardha",
  "Washim",
  "Yavatmal",
];

// talukas.ts

export const MAHARASHTRA_TALUKAS: { [key: string]: string[] } = {
  Ahmednagar: [
    "Ahmednagar",
    "Akole",
    "Jamkhed",
    "Karjat",
    "Kopargaon",
    "Nevasa",
    "Parner",
    "Pathardi",
    "Rahata",
    "Rahuri",
    "Sangamner",
    "Shevgaon",
    "Shrigonda",
    "Shrirampur",
  ],
  Akola: ["Akola", "Balapur", "Barshitakli", "Murtijapur", "Patur", "Telhara"],
  Amravati: [
    "Achalpur",
    "Amravati",
    "Anjangaon",
    "Bhatkuli",
    "Chandurbazar",
    "Chandur Railway",
    "Daryapur",
    "Dhamangaon Railway",
    "Morshi",
    "Nandgaon-Khandeshwar",
    "Teosa",
    "Warud",
  ],
  Aurangabad: [
    "Aurangabad",
    "Kannad",
    "Gangapur",
    "Khuldabad",
    "Paithan",
    "Phulambri",
    "Sillod",
    "Soegaon",
    "Vaijapur",
  ],
  Beed: [
    "Ambejogai",
    "Ashti",
    "Beed",
    "Dharur",
    "Georai",
    "Kaij",
    "Majalgaon",
    "Parli",
    "Patoda",
    "Shirur (Kasars)",
    "Wadwani",
  ],
  Bhandara: ["Bhandara", "Lakhani", "Mohadi", "Pauni", "Sakoli", "Tumsar"],
  Buldhana: [
    "Buldhana",
    "Chikhli",
    "Deulgaon Raja",
    "Jalgaon (Jamod)",
    "Khamgaon",
    "Lonar",
    "Malkapur",
    "Mehkar",
    "Motala",
    "Nandura",
    "Sangrampur",
    "Shegaon",
    "Sindkhed Raja",
  ],
  Chandrapur: [
    "Bhadrawati",
    "Brahmapuri",
    "Chandrapur",
    "Gondpipri",
    "Jiwati",
    "Korpana",
    "Mul",
    "Nagbhid",
    "Pombhurna",
    "Rajura",
    "Saoli",
    "Sindewahi",
    "Warora",
  ],
  Dhule: ["Dhule", "Sakri", "Shirpur", "Sindkheda"],
  Gadchiroli: [
    "Aheri",
    "Armori",
    "Bhamragad",
    "Chamorshi",
    "Dhanora",
    "Etapalli",
    "Gadchiroli",
    "Kurkheda",
    "Mulchera",
    "Sironcha",
  ],
  Gondia: [
    "Amgaon",
    "Arjuni Morgaon",
    "Deori",
    "Gondia",
    "Goregaon",
    "Salekasa",
    "Sadak Arjuni",
    "Tirora",
  ],
  Hingoli: ["Aundha (Nagnath)", "Basmath", "Hingoli", "Kalamnuri", "Sengaon"],
  Jalgaon: [
    "Amalner",
    "Bhadgaon",
    "Bhusawal",
    "Bodwad",
    "Chalisgaon",
    "Chopda",
    "Dharangaon",
    "Erandol",
    "Jalgaon",
    "Jamner",
    "Muktainagar",
    "Pachora",
    "Parola",
    "Raver",
    "Yawal",
  ],
  Jalna: [
    "Ambad",
    "Badnapur",
    "Bhokardan",
    "Ghansawangi",
    "Jafrabad",
    "Jalna",
    "Mantha",
    "Partur",
  ],
  Kolhapur: [
    "Ajara",
    "Bavda",
    "Bhudargad",
    "Chandgad",
    "Gadhinglaj",
    "Hatkanangale",
    "Kagal",
    "Karveer",
    "Panhala",
    "Radhanagari",
    "Shahuwadi",
    "Shirol",
  ],
  Latur: [
    "Ahmedpur",
    "Ausa",
    "Chakur",
    "Deoni",
    "Jalkot",
    "Latur",
    "Nilanga",
    "Renapur",
    "Shirur (Anantpal)",
    "Udgir",
  ],
  "Mumbai City": [
    "A Ward",
    "B Ward",
    "C Ward",
    "D Ward",
    "E Ward",
    "F North",
    "F South",
    "G North",
    "G South",
  ],
  "Mumbai Suburban": ["Andheri", "Borivali", "Kurla"],
  Nagpur: [
    "Bhiwapur",
    "Hingna",
    "Kalameshwar",
    "Kamthi",
    "Katol",
    "Kuhi",
    "Mauda",
    "Nagpur (Rural)",
    "Nagpur (Urban)",
    "Narkhed",
    "Parshivni",
    "Ramtek",
    "Savner",
    "Umred",
  ],
  Nanded: [
    "Ardhapur",
    "Bhokar",
    "Biloli",
    "Deglur",
    "Dharmabad",
    "Hadgaon",
    "Himayatnagar",
    "Kandhar",
    "Kinwat",
    "Loha",
    "Mahur",
    "Mukhed",
    "Mudkhed",
    "Naigaon (Khairgaon)",
    "Nanded",
  ],
  Nandurbar: [
    "Akkalkuwa",
    "Akrani",
    "Nandurbar",
    "Navapur",
    "Shahada",
    "Taloda",
  ],
  Nashik: [
    "Baglan",
    "Chandwad",
    "Deola",
    "Dindori",
    "Igatpuri",
    "Kalwan",
    "Malegaon",
    "Nashik",
    "Niphad",
    "Peth",
    "Sinnar",
    "Surgana",
    "Trimbakeshwar",
    "Yeola",
  ],
  Osmanabad: [
    "Bhoom",
    "Kalamb",
    "Lohara",
    "Osmanabad",
    "Paranda",
    "Tuljapur",
    "Umarga",
    "Washi",
  ],
  Palghar: [
    "Dahanu",
    "Jawhar",
    "Mokhada",
    "Palghar",
    "Talasari",
    "Vasai",
    "Vikramgad",
    "Wada",
  ],
  Parbhani: [
    "Gangakhed",
    "Jintur",
    "Manwath",
    "Parbhani",
    "Pathri",
    "Purna",
    "Palam",
    "Sonpeth",
  ],
  Pune: [
    "Ambegaon",
    "Baramati",
    "Bhor",
    "Daund",
    "Haveli",
    "Indapur",
    "Junnar",
    "Khed",
    "Maval",
    "Mulshi",
    "Pune City",
    "Purandar",
    "Shirur",
    "Velhe",
  ],
  Raigad: [
    "Alibag",
    "Khalapur",
    "Karjat",
    "Mahad",
    "Mangaon",
    "Mhasala",
    "Murud",
    "Panvel",
    "Pen",
    "Poladpur",
    "Roha",
    "Shrivardhan",
    "Sudhagad",
    "Uran",
  ],
  Ratnagiri: [
    "Chiplun",
    "Dapoli",
    "Guhagar",
    "Khed",
    "Lanja",
    "Mandangad",
    "Rajapur",
    "Ratnagiri",
    "Sangameshwar",
  ],
  Sangli: [
    "Atpadi",
    "Jat",
    "Kadegaon",
    "Kavathe Mahankal",
    "Khanapur",
    "Miraj",
    "Palus",
    "Shirala",
    "Tasgaon",
    "Valva-Islampur",
  ],
  Satara: [
    "Jaoli",
    "Khandala",
    "Khatav",
    "Mahabaleshwar",
    "Man",
    "Patan",
    "Phaltan",
    "Satara",
    "Wai",
  ],
  Sindhudurg: [
    "Devgad",
    "Kankavli",
    "Kudal",
    "Malvan",
    "Sawantwadi",
    "Vengurla",
  ],
  Solapur: [
    "Akkalkot",
    "Barshi",
    "Karmala",
    "Madha",
    "Malshiras",
    "Mangalvedha",
    "Mohol",
    "Pandharpur",
    "Sangole",
    "Solapur North",
    "Solapur South",
  ],
  Thane: [
    "Ambarnath",
    "Bhiwandi",
    "Kalyan",
    "Murbad",
    "Shahapur",
    "Thane",
    "Ulhasnagar",
  ],
  Wardha: [
    "Arvi",
    "Ashti",
    "Deoli",
    "Hinganghat",
    "Karanja",
    "Samudrapur",
    "Seloo",
    "Wardha",
  ],
  Washim: ["Karanja", "Malegaon", "Mangrulpir", "Manora", "Risod", "Washim"],
  Yavatmal: [
    "Arni",
    "Babhulgaon",
    "Darwha",
    "Digras",
    "Ghatanji",
    "Kalamb",
    "Mahagaon",
    "Maregaon",
    "Ner",
    "Pusad",
    "Ralegaon",
    "Umarkhed",
    "Wani",
    "Yavatmal",
    "Zari Jamni",
  ],
};
